# Site settings
name: Yuxuan Xiong
title: Yuxuan Xiong
description:
  Full-stack software engineer with a focus on intuitive user interfaces, scalable server architecture, and optimized database solutions
url: https://gyoxxi.github.io/
baseurl: ''
email: xyxnusstu@gmail.com
#cover:
logo: https://gyoxxi.github.io/img/emojis/technologist.png
resume: https://gyoxxi.github.io/resume.pdf
social:
  - title: email
    url: mailto:xyxnusstu@gmail.com
  - title: github
    url: https://github.com/gyoxxi
  - title: linkedin
    url: https://www.linkedin.com/in/yuxuan-xiong-b787341b7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
